/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pwjaphqqlwtobdfogagx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3amFwaHFxbHd0b2JkZm9nYWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1MzIyOTMsImV4cCI6MjA4NjEwODI5M30.v_rB-EtkLfF40M3FHvKarD0f3ES9RihDAX-KhOkIHFs"